# Generated by Django 5.1.6 on 2025-02-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('dificuldade_visao', models.IntegerField(choices=[(0, 'Normal'), (1, 'Leve'), (2, 'Moderada'), (3, 'Severa')])),
                ('media_humanas', models.FloatField()),
                ('media_linguagens', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.IntegerField()),
                ('colunas', models.IntegerField()),
                ('tipo_agrupamento', models.CharField(choices=[('sozinho', 'Sozinho'), ('dupla', 'Dupla'), ('trio', 'Trio')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='evento_capa/')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('aula', models.CharField(max_length=100)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('global_nota', models.FloatField()),
                ('parcial1_nota', models.FloatField(blank=True, null=True)),
                ('parcial2_nota', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('coluna', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('mapeamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mapeamento')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escola')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escola')),
            ],
        ),
        migrations.CreateModel(
            name='PDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.turma'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professorcurso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turma'),
        ),
    ]
