# Generated by Django 5.1.7 on 2025-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('comprovante_residencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='Id',
            field=models.CharField(default='default_id_value', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='media_exatas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='000000000000', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media_humanas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media_linguagens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
