# Generated by Django 5.1.7 on 2025-03-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_responsavel_aluno_id_aluno_media_exatas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Id',
            new_name='id_aluno',
        ),
    ]
