# Generated by Django 5.1.7 on 2025-03-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_aluno_id_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='id_aluno',
            new_name='matricula_aluno',
        ),
    ]
