# Generated by Django 5.1.7 on 2025-03-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_escola_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
