# Generated by Django 5.2.1 on 2025-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='media_exatas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media_humanas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='media_linguagens',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
