# Generated by Django 5.2.1 on 2025-06-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_aluno_media_exatas_alter_aluno_media_humanas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula_aluno',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='api.professorcurso'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='api.turma'),
        ),
        migrations.AlterField(
            model_name='eventoescolar',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.escola'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='api.aluno'),
        ),
        migrations.AlterField(
            model_name='mapeamento',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamento', to='api.turma'),
        ),
        migrations.AlterField(
            model_name='materialdeestudo',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='materialdeestudo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='api.turma'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.aluno'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdt', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdt', to='api.turma'),
        ),
        migrations.AlterField(
            model_name='posicaoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='api.aluno'),
        ),
        migrations.AlterField(
            model_name='posicaoaluno',
            name='mapeamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='api.mapeamento'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='api.escola'),
        ),
        migrations.AlterField(
            model_name='professorcurso',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='api.escola'),
        ),
    ]
