# Generated by Django 5.2.1 on 2025-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aluno_matricula_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='media_exatas',
            field=models.FloatField(default=0),
        ),
    ]
